### ISSUE TITLE
Is LOGGING_VERSION relevant?

### ISSUE THREAD

**Issue by mattbaker-digital** [JSC-TechMinds/Arduino-Log#3]
It seems to have been last changed in d05e81f886b2db51ed84be0f18feaed2ad5e587e
https://github.com/JSC-electronics/Arduino-Log/commit/d05e81f886b2db51ed84be0f18feaed2ad5e587e#diff-0d2c0792efce3ec348c672fa5b666201dc34066557c2f2f97879aec45e40e6b0R40

**Comment by vzahradnik** [comment]
It looks like you're right. As long as the tests pass, it should be safe to remove.

**Comment by vzahradnik** [comment]
Removed in 21ccaa8a61352f78770ad6335225457cd2c14787.
